---

- hosts: ngnix
  remote_user: root
  become: yes
  become_method: sudo

  tasks:
  - name: Install Nginx of ubuntu 16.04
    apt: name=nginx update_cache=yes state=latest

  - name: Start Nginx and boot
    service: name=nginx state=started enabled=yes

  - name: Install PHP-FPM of ubuntu 16.04
    apt: name=php-fpm update_cache=yes state=latest
  - name: Install mysql of ubuntu 16.04
    apt: name=mysql-server update_cache=yes state=latest
